services:
  # 1. Servicio de Base de Datos (PostgreSQL)
  - type: postgres # CAMBIO CLAVE: Usa 'postgres' para crear la BD Add-on
    name: mi-django-db
    plan: free
    region: oregon 
    # El resto de la configuración de la BD la maneja Render

  # 2. Servicio Web (Django/Gunicorn)
  - type: web
    name: mi-django-app
    # Render usará tu Dockerfile, pero aquí definimos el plan y la región.
    plan: free
    region: oregon 
    autoDeploy: true
    branch: main
    
    # Se le indica a Render que la imagen debe ser construida con Dockerfile
    env: docker 
    
    # Render busca el comando de inicio (gunicorn...) en tu Dockerfile.
    # Por lo tanto, ¡ELIMINAMOS la línea 'startCommand'!
    
    # IMPORTANTE: Reemplaza buildCommand por postDeployCommand para las migraciones
    # buildCommand es para el proceso de Dockerfile, no para comandos de Django.
    postDeployCommand: "python manage.py migrate" 
    
    # Otras configuraciones
    numInstances: 1
    
    # Conexión a la Base de Datos
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-django-db
          property: connectionString
      - key: WEB_HOST
        value: mi-django-app.onrender.com