services:
  # 1. Servicio de Base de Datos (PostgreSQL)
  - type: pserv # Tipo de servicio persistente
    name: mi-django-db
    plan: free
    region: oregon 
    disk:
      name: postgres-disk
      sizeGB: 1

  # 2. Servicio Web (Django/Gunicorn)
  - type: web
    name: mi-django-app
    plan: free
    region: oregon 
    autoDeploy: true
    branch: main
    env: docker 
    
    numInstances: 1
    
    # Conexi√≥n a la Base de Datos (Crea la variable DATABASE_URL para la app)
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-django-db
          property: connectionString
      - key: WEB_HOST
        value: mi-django-app.onrender.com