services:
  # 1. Servicio de Base de Datos (pserv)
  - type: pserv 
    name: mi-django-db
    plan: free
    region: oregon 
    
  # 2. Servicio Web (Django/Gunicorn)
  - type: web
    name: mi-django-app
    plan: free
    region: oregon 
    autoDeploy: true
    branch: master
    
    env: docker # CORRECCIÓN: Usar 'env: docker' para construir desde Dockerfile
    
    # ESTO EJECUTA LA MIGRACIÓN AUTOMÁTICAMENTE DESPUÉS DE CADA DESPLIEGUE EXITOSO
    postDeployCommand: "python manage.py migrate" 
    
    numInstances: 1
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-django-db-fake
          property: connectionString
      - key: WEB_HOST
        value: mi-django-app.onrender.com