services:
  - type: web
    name: mi-django-app
    plan: free
    region: oregon
    autoDeploy: true
    branch: main
    runtime: docker
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-django-db
          property: connectionString
      - key: WEB_HOST
        value: mi-django-app.onrender.com
