services:
  # 1. Servicio de Base de Datos (PostgreSQL)
  - type: pserv
    name: mi-django-db
    plan: free
    region: oregon

  # 2. Servicio Web (Django en Docker)
  - type: web
    name: mi-django-app
    plan: free
    region: oregon
    autoDeploy: true
    branch: main
    
    env: docker # <-- ESTE ES EL CAMBIO CLAVE para indicar que use el Dockerfile
    
    numInstances: 1

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-django-db
          property: connectionString
      - key: WEB_HOST
        value: mi-django-app.onrender.com