services:
  - type: pserv
    name: mi-django-db
    plan: free
    region: oregon

  - type: web
    name: mi-django-app
    plan: free
    region: oregon
    autoDeploy: true
    branch: main
    runtime: docker  
    startCommand: "gunicorn django_docker_prueba.wsgi:application --bind 0.0.0.0:$PORT"
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-django-db
          property: connectionString
      - key: WEB_HOST
        value: mi-django-app.onrender.com
