services:
  # 1. Servicio de Base de Datos (PostgreSQL)
  - type: pserv # CORRECCIÓN FINAL: Usamos 'pserv' (Persistent Service)
    name: mi-django-db
    plan: free
    region: oregon 
    # ELIMINAMOS TODA LA SECCIÓN 'disk:' Y SUS SUB-PROPIEDADES.
    
  # 2. Servicio Web (Django/Gunicorn)
  - type: web
    name: mi-django-app
    plan: free
    region: oregon 
    autoDeploy: true
    branch: main
    env: docker 
    
    numInstances: 1
    
    # Conexión a la Base de Datos (Crea la variable DATABASE_URL para la app)
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-django-db
          property: connectionString
      - key: WEB_HOST
        value: mi-django-app.onrender.com