services:
  # 1. Servicio de Base de Datos (PostgreSQL)
  - type: pserv
    name: mi-django-db
    plan: free
    region: oregon # O la región que elijas, debe coincidir con el web service
    # Esto es solo si necesitas persistencia de datos

  # 2. Servicio Web (Django/Gunicorn)
  - type: web
    name: mi-django-app
    # Render usará tu Dockerfile, pero aquí definimos el plan y la región.
    plan: free
    region: oregon # Debe coincidir con la base de datos
    autoDeploy: true
    branch: main
    # Render ejecutará el CMD de tu Dockerfile (Gunicorn)
    env: docker
    
    # Comandos de post-despliegue (Ejecución de migraciones)
    numInstances: 1
    buildCommand: "./build.sh" # Opcional: puedes ejecutar scripts complejos aquí si es necesario
    startCommand: "gunicorn pruebaproyecto.wsgi:application --bind 0.0.0.0:$PORT"
    
    # Conexión a la Base de Datos
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-django-db
          property: connectionString
      - key: WEB_HOST
        value: mi-django-app.onrender.com # Tu dominio final