services:
  # 1. PostgreSQL
  - type: pserv
    name: mi-django-db
    plan: free
    region: oregon

  # 2. Django con Dockerfile
  - type: web
    name: mi-django-app
    plan: free
    region: oregon
    autoDeploy: true
    branch: main

    numInstances: 1

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-django-db
          property: connectionString

      - key: WEB_HOST
        value: mi-django-app.onrender.com
